boardGame: Board Class Reference
Board Class Reference
#include <board.h>
Public Types
enum state { PLAYER = 'P', EXIT = 'X', WALL = 'W', EMPTY = '.' }
Public Member Functions
Board ()
Board (int boardSize)
void setState (int, int, char)
void displayBoard ()
int getSize ()
char getState (int, int)
Private Attributes
int _boardSize
char _board [15][15]
Detailed Description
board.h
Created on: May 2, 2016 Author: Beven
Definition at line 13 of file board.h.
Member Enumeration Documentation
enum Board::state
enum state present the type of the board point.
Enumerator:
PLAYER
Location of the Player.
EXIT
Location of the Exit.
WALL
Location of the Wall.
EMPTY
Present the path that player can walk through.
Definition at line 26 of file board.h.
Constructor & Destructor Documentation
Board::Board ()
Constructor
Definition at line 14 of file board.cpp.
References _boardSize.
Board::Board (int boardSize)
Constructor
Parameters:
boardSize N*N board size filled with '.'.
Definition at line 22 of file board.cpp.
References _board, _boardSize, and EMPTY.
Member Function Documentation
void Board::displayBoard ()
Display the state of the board, show where is the player, walls and exit.
Definition at line 48 of file board.cpp.
References _board, and _boardSize.
Referenced by Game::displayBoard().
int Board::getSize ()
Get the size of the board.
Returns:
N*N demension of the board.
Definition at line 64 of file board.cpp.
References _boardSize.
Referenced by Game::initBoard().
char Board::getState (int row, int col)
Get the specific state in the board.
Parameters:
row
col
Returns:
element 'P', '.', 'W', 'E'.
Definition at line 75 of file board.cpp.
References _board.
Referenced by Game::initBoard(), and Game::move().
void Board::setState (int row, int col, char state)
Set the element in the board.
Parameters:
row
col
state
Definition at line 40 of file board.cpp.
References _board.
Referenced by Game::initBoard(), Game::move(), and GameManager::resetGame().
Member Data Documentation
char Board::_board[15][15] [private]
Definition at line 16 of file board.h.
Referenced by Board(), displayBoard(), getState(), and setState().
int Board::_boardSize [private]
Definition at line 15 of file board.h.
Referenced by Board(), displayBoard(), and getSize().
The documentation for this class was generated from the following files:
include/board.h
src/board.cpp