boardGame: GameManager Class Reference
GameManager Class Reference
#include <gameManager.h>
Public Member Functions
GameManager ()
Game * createGame ()
std::string rename ()
Game * switchGame ()
Game * resetGame ()
Game * chooseGame (int)
void showState ()
void playGame (std::string)
Private Attributes
int gameSum
int gameId
Game * gameUsing
Game * games [5]
Detailed Description
Definition at line 17 of file gameManager.h.
Constructor & Destructor Documentation
GameManager::GameManager ()
Constructor Manager user to control the progress of the board games.
Definition at line 20 of file gameManager.cpp.
References createGame(), gameId, and gameSum.
Member Function Documentation
Game * GameManager::chooseGame (int gameId)
Choose a game.
Parameters:
gameId game id
Returns:
Game pointer.
Definition at line 88 of file gameManager.cpp.
References Game::displayBoard(), and games.
Referenced by switchGame().
Game * GameManager::createGame ()
Create a new game.
Returns:
The point of the created game.
Definition at line 31 of file gameManager.cpp.
References games, gameSum, and gameUsing.
Referenced by GameManager(), and main().
void GameManager::playGame (std::string direction)
Play the game and move player to the direction.
Parameters:
direction 'u', 'd', 'l', 'r'.
Definition at line 113 of file gameManager.cpp.
References gameUsing, Game::moveDown(), Game::moveLeft(), Game::moveRight(), and Game::moveUp().
Referenced by main().
std::string GameManager::rename ()
Change the name of the game.
Returns:
the new name of the game.
Definition at line 46 of file gameManager.cpp.
References gameUsing, Game::getName(), and Game::setName().
Referenced by main().
Game * GameManager::resetGame ()
Reset the current game, set the player's location to (0,0).
Returns:
game's pointer
Definition at line 72 of file gameManager.cpp.
References Game::_board, Game::_col, Game::_row, Game::displayBoard(), Board::EMPTY, gameUsing, Board::PLAYER, and Board::setState().
Referenced by main().
void GameManager::showState ()
Show the states of the games, game names, which game is playing.
Definition at line 98 of file gameManager.cpp.
References Game::displayBoard(), games, gameSum, gameUsing, and Game::getName().
Referenced by main().
Game * GameManager::switchGame ()
Switch to another game.
Returns:
game's pointer which switch to.
Definition at line 60 of file gameManager.cpp.
References chooseGame(), and gameUsing.
Referenced by main().
Member Data Documentation
int GameManager::gameId [private]
Definition at line 21 of file gameManager.h.
Referenced by GameManager().
Game* GameManager::games[5] [private]
Definition at line 23 of file gameManager.h.
Referenced by chooseGame(), createGame(), and showState().
int GameManager::gameSum [private]
Definition at line 20 of file gameManager.h.
Referenced by createGame(), GameManager(), and showState().
Game* GameManager::gameUsing [private]
Definition at line 22 of file gameManager.h.
Referenced by createGame(), playGame(), rename(), resetGame(), showState(), and switchGame().
The documentation for this class was generated from the following files:
include/gameManager.h
src/gameManager.cpp