boardGame: Game Class Reference
Game Class Reference
#include <game.h>
Public Member Functions
Game (int)
void initBoard ()
void displayBoard ()
std::string getName ()
std::string setName (std::string name)
void move (int row, int col)
void moveUp ()
void moveDown ()
void moveRight ()
void moveLeft ()
Public Attributes
int _row
int _col
Board _board
std::string _gameName
Detailed Description
Definition at line 22 of file game.h.
Constructor & Destructor Documentation
Game::Game (int boardSize)
Constructor
Parameters:
boardSize N*N board
Definition at line 18 of file game.cpp.
References _board, _col, _gameName, _row, and initBoard().
Member Function Documentation
void Game::displayBoard ()
Display the game state.
Definition at line 64 of file game.cpp.
References _board, and Board::displayBoard().
Referenced by GameManager::chooseGame(), initBoard(), move(), GameManager::resetGame(), and GameManager::showState().
std::string Game::getName ()
Get the name of the game.
Returns:
name of the game.
Definition at line 104 of file game.cpp.
References _gameName.
Referenced by GameManager::rename(), and GameManager::showState().
void Game::initBoard ()
Init the game, init the board with elements.
Definition at line 30 of file game.cpp.
References _board, _col, _row, displayBoard(), Board::EMPTY, Board::EXIT, Board::getSize(), Board::getState(), Board::PLAYER, Board::setState(), and Board::WALL.
Referenced by Game().
void Game::move (int row, int col)
Move the player to the set location.
Parameters:
row
col
Definition at line 74 of file game.cpp.
References _board, _col, _row, displayBoard(), Board::EMPTY, Board::EXIT, Board::getState(), Board::PLAYER, Board::setState(), and Board::WALL.
Referenced by moveDown(), moveLeft(), moveRight(), and moveUp().
void Game::moveDown ()
Move the player to the down direction.
Definition at line 130 of file game.cpp.
References _col, _row, and move().
Referenced by GameManager::playGame().
void Game::moveLeft ()
Move the player to the left direction.
Definition at line 146 of file game.cpp.
References _col, _row, and move().
Referenced by GameManager::playGame().
void Game::moveRight ()
Move the player to the right direction.
Definition at line 138 of file game.cpp.
References _col, _row, and move().
Referenced by GameManager::playGame().
void Game::moveUp ()
Move the player to the up direction.
Definition at line 122 of file game.cpp.
References _col, _row, and move().
Referenced by GameManager::playGame().
std::string Game::setName (std::string name)
Set name for the game.
Parameters:
name
Returns:
Definition at line 114 of file game.cpp.
References _gameName.
Referenced by GameManager::rename().
Member Data Documentation
Board Game::_board
Definition at line 27 of file game.h.
Referenced by displayBoard(), Game(), initBoard(), move(), and GameManager::resetGame().
int Game::_col
Definition at line 26 of file game.h.
Referenced by Game(), initBoard(), move(), moveDown(), moveLeft(), moveRight(), moveUp(), and GameManager::resetGame().
std::string Game::_gameName
Definition at line 28 of file game.h.
Referenced by Game(), getName(), and setName().
int Game::_row
Definition at line 25 of file game.h.
Referenced by Game(), initBoard(), move(), moveDown(), moveLeft(), moveRight(), moveUp(), and GameManager::resetGame().
The documentation for this class was generated from the following files:
include/game.h
src/game.cpp